name: probabilistic-submodular-models

# dictionary of sampler options
sampler:

  # parameters related to the Gibbs sampler
  gibbs:

    # ratio of initial burn-in time w.r.t. the total number of iteration of the sampling method.
    # Bounds: (0, 1)
    burn_in_ratio: 0.2

  # parameters related to the Metropolis sampler
  metropolis:

    # probability of removing an element v \in S if v is also \in X.
    # Bounds: (0, 1)
    p_remove: 0.1

    # ratio of initial burn-in time w.r.t. the total number of iteration of the sampling method.
    # Bounds: (0, 1)
    burn_in_ratio: 0.2

  # parameters related to the Frank-Wolfe Metropolis sampler
  lovasz_projection:  
    # ratio of initial burn-in time w.r.t. the total number of iteration of the sampling method.
    # Bounds: (0, 1)
    burn_in_ratio: 0.2

    # step size of the subgradient projected descent
    eta: 0.01

    # momentum of the subgradient projected descent
    momentum: 0.005

    # standard deviation of the normal noise
    std: 1

# dictionary of set-submodular functions
objectives:

  # synthetic monotone function: summation of non-negative random weights
  demo_monotone:

    # size of the ground set
    n: 3

  # synthetic non-monotone function: summation of possibly negative random weights
  demo_non_monotone:

    # size of the ground set
    n: 20

selected:
  # set-submodular function to mix from
  objective: 'demo_monotone'

  # number of samples
  M: 50

  # set to 1 to print debug info, 0 otherwise
  verbose: 1
