name: probabilistic-submodular-models

defaults:
  - _self_

  # selected probabilistic submodular model
  - obj: 'demo_monotone'
  
  # specify the type of sample size
  - sample_size: 'small'

  # specify the sampler
  - sampler: 'gibbs'

  # run multiple configurations in parallel
  - override hydra/launcher: joblib

selected:

  # ratio of initial burn-in time w.r.t. the total number of iteration of the sampling method.
  # Bounds: (0, 1)
  burn_in_ratio: 0.2

  # set to 1 to print debug info, 0 otherwise
  verbose: 1
